### ISSUE TITLE
How to have the bot send a message in response to a user-defined event

### ISSUE THREAD

**Issue by qirtaiba** [wireapp/bot-sdk-node#11]
This is not a bug in the SDK, but just a general support request.  I'm not sure if this is the right place for it; if there is somewhere else that I should post please let me know.

I want my bot to send messages in response to an event that I have defined, that isn't a user message, member leaving, joining, or renaming of the conversation.  It's actually a JSON message that I send at the bot, which is similar to the JSON from a user message.

I know that the bot receives this message because it logs to the console correctly.  But the actual sending of a message by the bot in response isn't working.  Here is the code that I've added to lib/service.js which is a simplified version of the message sending routine conversationMessageAdd (with the OTR decoding stuff taken out, as the text of the message to send doesn't come from a conversation):

`  conversationPlainMessageAdd(req, data, res, botID) {`
`      console.log("New plain message for bot ${botID}, data: ${JSON.stringify(data)}");`
`      this.bots[botID].httpsClient.sendMessage(data, false, (response, status) => {`
`        console.log("message successfully sent with status ${status}");`
`      });`
`      Service.sendResponse(res, 200);`
`  }`

It correctly logs what I want it to do, but fails to actually send the message (the "httpsClient.sendMessage" line).  It says "sent with status 400" which means bad request suggesting that my JSON is malformed.  But when I compare my JSON to the JSON from a user message, they are almost identical (except for the OTR encoding), and also my JSON validates correctly using a validator:

Mine: `New plain message for bot 81040220-087b-4f26-9a93-7ee524b692c1, data: {"conversation":"7e791e68-bc81-4ebf-8524-0fedbe51cccd","time":"2017-05-03T12:57:48.223Z","data":{"text":"Plain text test message","sender":"50e6dd4de98bfff2","recipient":"b987588fb6707108"},"from":"323906e5-2216-23f9-823e-92c8925f6c23","type":"conversation.plain-message-add"}`

User message: `New message for bot 81040220-087b-4f26-9a93-7ee524b692c1, data: {"conversation":"7e791e68-bc81-4ebf-8524-0fedbe51cccd","time":"2017-05-03T12:57:48.223Z","data":{"text":"owABAaEAWCB02aI7LySbnfjnyok7RouExXUW/+gjVeN2JQgncO6eXAJYbQGlAFCF7Fis1n7/Sk0ngryTEitoAQACAQOhAFggqmDd/C0+TZx84QUOAW4AW4yJtIug+vOHNVXgvD2CjzwEWC3jkjbqDRX89BxKYj4KSP9QSOfG4wp1W0wjThg3DDX9rR7kAx5EMOb+att4E/w=","sender":"50e6dd4de98bfff2","recipient":"b987588fb6707108"},"from":"323906e5-2216-23f9-823e-92c8925f6c23","type":"conversation.otr-message-add"}`

Thanks.

PS. The bot, user and conversation IDs above have been falsified.
PPS. It's just test code, I haven't included the checking that will be used in production.

**Comment by dkovacevic** [comment]
You are getting 400 from the Backend as `"type":"conversation.plain-message-add"` is not recognized/allowed. In order to send a message to Wire Backend you must set:
`"type":"conversation.otr-message-add"`
All the traffic on Wire must be OTR ( encrypted). Wire does not support plain text messages anymore.
However you could potentially send a custom message that is not one of:
```
message GenericMessage {
  required string message_id = 1; // client generated random id, preferably UUID
  oneof content {
    Text text = 2;
    ImageAsset image = 3;
    Knock knock = 4;
    LastRead lastRead = 6;
    Cleared cleared = 7;
    External external = 8;
    ClientAction clientAction = 9;
    Calling calling = 10;
    Asset asset = 11;
    MessageHide hidden = 12;
    Location location = 13;
    MessageDelete deleted = 14;
    MessageEdit edited = 15;
    Confirmation confirmation = 16;
    Reaction reaction = 17;
    Ephemeral ephemeral = 18;
  }
}
```
but in that case you would have to build your own Wire Client that would be able to receive this new custom message type. Take a look at the message.proto file to see how other protos are defined.

Hope this helps..

**Comment by qirtaiba** [comment]
OK thanks, that's helpful, it seems I can just OTR encrypt the message so I'll try to do that.
