### ISSUE TITLE
Unable to add bot ("everyone left") but Devbot says "all good"

### ISSUE THREAD

**Issue by wizzard0** [wireapp/bot-sdk-node#17]
Repro: 

> oleksandr
> test bot wiz2bot
> 14:50 Dev
> All good!

(visit URL)
(conversation opens, "everyone left")

**Comment by wizzard0** [comment]
@qirtaiba maybe you've seen "Everyone left" too?

**Comment by qirtaiba** [comment]
No I haven't had that problem.

**Comment by dkovacevic** [comment]
Unfortunately we had to discontinue `wire.com/b/<botName>` links :(. If you go and ask Don to enable your bot now you would type new type of invite link. Something like:
`https://app.wire.com?bot_name=echo&bot_provider=d39b462f-7e60-4d88-82e1-44d632f94901&bot_service=7908f9be-df93-4c84-b7c4-21b83ce83d1e`

However this link is not yet operational as it requires new version of Web App (that is coming on 8th of November)
If you are impatient you could use Dev Web App and change the bot_provider/bot_service like here:
https://wire-webapp-dev.wire.com/?env=prod&bot_name=echo&bot_provider=d39b462f-7e60-4d88-82e1-44d632f94901&bot_service=7908f9be-df93-4c84-b7c4-21b83ce83d1e

Alternatively (while using Dev Web App) you could add bots through console by running: `wire.app.repository.bot.add_bot({botName: "Name", botProvider: "d39b462f-7e60-4d88-82e1-44d632f94901", botService: "7908f9be-df93-4c84-b7c4-21b83ce83d1e"}, true)`

Give it a try and let us know

Thanks,
Dejan

**Comment by wizzard0** [comment]
Hi Dejan,

I'm able to successfully add hello bot via URL and via console, with my own bot, not so much:
```
wire.app.repository.bot.add_bot({botName: "wiz2bot", botProvider: "4206cc25-17ea-44c8-bdf4-09559223b9d7", botService: "4bfaf7be-0625-41c8-853a-b562e88cf023"}, true)
Promise {[[PromiseStatus]]: "pending", [[PromiseValue]]: undefined}
prod-nginz-https.wire.com/conversations/e210e510-58ef-4514-8678-db1da561f319/bots:1 POST https://prod-nginz-https.wire.com/conversations/e210e510-58ef-4514-8678-db1da561f319/bots 502 (Bad Gateway)
```

**Comment by wizzard0** [comment]
Also note that the server logs GET/POST requests when testing, but nothing when adding.

**Comment by dkovacevic** [comment]
Hi,

looks like you have problems with your certificate.
This is what I see in our logs:
<img width="965" alt="screen shot 2017-11-05 at 16 00 10" src="https://user-images.githubusercontent.com/4378852/32415994-8d5397ee-c242-11e7-866c-7152cc9dc1c9.png">

Feel free to contact me on Wire (username: `@dejan`) so we debug your both together.

Thanks
Dejan

**Comment by wizzard0** [comment]
Hmm, certificate problems are interesting, because I use a letsencrypt cert, Chrome doesn't show any issues with it - 
![image](https://user-images.githubusercontent.com/424619/32417943-8b57c880-c269-11e7-9e34-2d40280e1924.png)

Also, um, which Dejan is you? :)
![image](https://user-images.githubusercontent.com/424619/32417945-9473e6b0-c269-11e7-900c-a639b160eee8.png)
i'm `@oleksandr_now`, for that matter

**Comment by dkovacevic** [comment]
Just search for: `@dejan`. That would do the work
