### ISSUE TITLE
Readme out of date

### ISSUE THREAD

**Issue by maxogden** [wireapp/bot-sdk-node#18]
Hi, I was able to register a bot with https://github.com/wireapp/don-bot and use this module successfully, but the readme here does not have working instructions for this method.

**Comment by dkovacevic** [comment]
Thanks. I've updated the invite line for Don.

**Comment by rubbyridge** [comment]
The Don invite link doesn't seem to be working in Firefox or Chrome, I just log into my account as normal. Am I missing something?

**Comment by dkovacevic** [comment]
Don's invite link works for Wire for Teams only now :(

You can use this shell instead: 
https://github.com/wireapp/echo-bot/blob/develop/myprovider.sh
