### ISSUE TITLE
Don bot link does not work

### ISSUE THREAD

**Issue by kmoe** [wireapp/bot-sdk-node#19]
The README says to visit the following link to register a bot:
https://app.wire.com/?bot_name=don&bot_provider=d39b462f-7e60-4d88-82e1-44d632f94901&bot_service=7a7e5417-0ea3-4608-a5ff-cb809b93f65a

However, when I click on this (in Chromium) it takes me to the wire client without opening a conversation with the Don bot user. Searching for this user (or "DevBot") also yields no results.

How can I register a bot?

**Comment by krzysztofkarolak** [comment]
I have the same problem.

**Comment by dkovacevic** [comment]
Unfortunately  Don works only for Teams now :(
https://github.com/wireapp/don-bot/issues/6
You can use the shell script we provide to register as bot developer and register new bots:
https://github.com/wireapp/echo-bot/blob/master/myprovider.sh

Thanks for checking the code and sorry for this :(

@marcoconti83

**Comment by marcoconti83** [comment]
Hi @JamieH ,

Thank you for taking part in the beta phase of integrations for Wire. After some initial experimentation with integrations, we decided to streamline this feature for teams.

You can create a team with a free month trial or join an existing team to keep using integrations; the link will work if you use a team account.

If setting up a team account is not an option for you, please get in touch with us and we'll be happy to look for a solution.

**Comment by marcoconti83** [comment]
Hi @krzysztofkarolak ,

Thank you for taking part in the beta phase of integrations for Wire. After some initial experimentation with integrations, we decided to streamline this feature for teams.

You can create a team with a free month trial or join an existing team to keep using integrations; the link will work if you use a team account.

If setting up a team account is not an option for you, please get in touch with us and we'll be happy to look for a solution.

**Comment by JamieH** [comment]
@marcoconti83 what's the best way to get in touch?

**Comment by marcoconti83** [comment]
Look me up on Wire, search for "@mc" handle.

**Comment by goesta** [comment]
So there is no support for Bots on personal accounts/groups?

**Comment by marcoconti83** [comment]
@goesta at the moment we are focusing on this feature only for teams. On the long run we are looking at other options for personal accounts.

**Comment by kmoe** [comment]
@marcoconti83 I've sent a contact request on Wire

**Comment by marcoconti83** [comment]
@kmoe 
thanks for reaching out, we had to change the process a little bit to make it more scalable, please shoot an email to support@wire.com and our amazing support team will take it from there and help you out.
