### ISSUE TITLE
sending Ephemeral messages

### ISSUE THREAD

**Issue by devzspy** [wireapp/bot-sdk-node#21]
What would be the proper steps to have my bot send an ephemeral message?

I checked against the lithium java bot for any existing code and I didn't see anything.

I figured I can treat it like sending a reaction (relates to #20 )  and I created a function in my bot_instance.js 

```javascript
 sendTimedMessage(message, cb) {
    const ephemeral = {
      message_id: uuidV1(),
      expire_after_millis: 15000,
      text: {
        content: message,
        mention: [],
        link_preview: [],
      },
    };
    this.service.sendMessage(this.botID, ephemeral, cb);
  }
```

I figured this was the correct way to do it based on the messages.proto structure.

However, when I trigger my sendTimedMessage function, it sends my message without a timeout.

**Comment by dkovacevic** [comment]
It's here:
https://github.com/wireapp/lithium/blob/develop/src/main/java/com/wire/bots/sdk/assets/Text.java#L48-L56

**Comment by devzspy** [comment]
Thanks! I will do what I can to figure out from here.
