### ISSUE TITLE
Mention a user

### ISSUE THREAD

**Issue by devzspy** [wireapp/bot-sdk-node#22]
I see in the messages.proto there is a way to mention someone. Does this actually highlight / notify that one specific individual?

I've figured out how to obtain the user_id but how would I go about obtaining the user_name of the user?

I don't see anything that actually does this in the lithium java bot.

I'd prefer to do this dynamically if possible.

Otherwise, I might just create a sqlite table that collects the user_id and user_name when a member joins the conversation and just perform that kind of mapping.

Thanks in advance

**Comment by dkovacevic** [comment]
Unfortunately mentions are not implemented the clients yet :(. It's planned for this summer.

You can get the profile info for the User like this:
https://github.com/wireapp/lithium/blob/develop/src/main/java/com/wire/bots/sdk/API.java#L121-L129

https://github.com/wireapp/lithium/blob/develop/src/main/java/com/wire/bots/sdk/server/model/User.java

**Comment by devzspy** [comment]
Thanks!
