### ISSUE TITLE
Instructions for registering bot no longer work

### ISSUE THREAD

**Issue by kalin** [wireapp/bot-sdk-node#23]
The "Don" link redirects to a standard user registration, however it seems that bot registration is still possible via API as seen and tested here:

https://adamluvshis.com/tags/wire-bot

Are the instructions outdated or is the bot API dead?

**Comment by devzspy** [comment]
So this is Adam Luvshis. You can message me on Wire under @aluvshis if you want. 

The Don not was moved to be utilized under teams if I am not mistaken. However, bit registration is still open and available.

You can use the shell script https://github.com/devzspy/bot-sdk-node/blob/master/myprovider.sh that was created by Dejan one of the wire bot developers. 

This shell script is where I pulled the API calls and listed them on my website

**Comment by dkovacevic** [comment]
Don is still up and running but like Adam said you have to have Wire for Teams :(
As Team Admin you then go and add this token
`59d7abe5-3850-4b34-8fe5-0bcd4bfad4e6:2a04f5d6-12ca-4c5a-812a-b82fd3767a04` under _Services_ tab
Don:
```
providerId: 59d7abe5-3850-4b34-8fe5-0bcd4bfad4e6
serviceId: 2a04f5d6-12ca-4c5a-812a-b82fd3767a04
```

Having Wire for Teams you can add various existing bots or your bots into conversations directly from the UI.
Like:
<img width="376" alt="screen shot 2018-10-10 at 21 46 48" src="https://user-images.githubusercontent.com/4378852/46761925-10b27a80-ccd6-11e8-9042-217e4755e150.png">

**Comment by taylorjdawson** [comment]
@devzspy @dkovacevic 
Just to be clear one is still able to create a bot for wire and use that bot outside of Wire for Teams?

Thanks! 👍

**Comment by dkovacevic** [comment]
@taylorjdawson You can develop and register your bot on Wire but only team users would be able to use it.

**Comment by taylorjdawson** [comment]
@dkovacevic So if I want to develop a chat bot and use it in a group chat I'd have to pay for Wire  teams and so would everyone else?

Is that's the case would it be possible to change that? 
Thanks!

**Comment by dkovacevic** [comment]
@taylorjdawson It's enough if only you would create your team and invite your friends as guests. In that case only you would have to pay $6/month which is nothing for such an awesome secure messenger that even has the dark theme ;)

**Comment by taylorjdawson** [comment]
@dkovacevic ahh okay that's not too bad! Will you have dev/opensource plans in the future?
