### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by ffflorian** [wireapp/bot-sdk-node#3]
So I created a new bot with Wire's `devbot` and fed him my public key. Now I added all the information (private key, port, etc.) to the [echo example](https://github.com/wireapp/bot-sdk-node/blob/master/example/echo_text_bot.js) - but when I start it, I receive an empty line. Nothing else.

When I check the output with `curl localhost:443` I receive
```
curl: (52) Empty reply from server
```

I am running Node.js 7.7.2 on Debian 8.

**Comment by ffflorian** [comment]
Alright, it was my mistake. The bot is running now, but every time I send him a message, I get an error:

```
(node:21566) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: Cannot read property '0' of undefined.
```

**Comment by damirn** [comment]
Did you update the 'auth' property in the object fed to createService?

**Comment by ffflorian** [comment]
> Did you update the 'auth' property in the object fed to createService?

Yes, of course.

Here is some more log:

```
New message for bot b409182a-4948-43ba-82dc-1413677d6b11, data: {"conversation":"455c63da-093b-46a6-82e9-78b12f918169","time":"2017-03-13T17:44:24.619Z","data":{"text":"owABAaEAWCAlp43NDnSJV6r5lVu2JagWMvbf9anAIUSwQ2Z4a8rtlQJYvQKkAAABoQBYIIz4614aYCzRXHj1Rz3n5EvJOffMO9JRNi39Psf223DqAqEAoQBYIOC3eK4Vi+GfsUb9rTHWc9QixF8I8ImERIYFtnjhgD8FA6UAUMDOKA5DPuOIQp1D3s/BgeMBAAIAA6EAWCANaQBPmEJ27YRdUC9uGimBllZhWOKOiGMP8nnRbWisXQRYLdos7n+N+DmyRIMgnAM1EOffx9Q9QKjwyeibARDAv9ePj9rJUqG5GrbjhE6XnQ==","sender":"8804a06b989632be","recipient":"8fa2d9790ffc8e80"},"from":"[redacted]","type":"conversation.otr-message-add"}
load_session 9bce80c5-ec4c-457e-a966-7eecee1674d9_8804a06b989632be
as json: {"conversation":"[455c63da-093b-46a6-82e9-78b12f918169]","time":"2017-03-13T17:44:24.619Z","data":{"text":"owABAaEAWCAlp43NDnSJV6r5lVu2JagWMvbf9anAIUSwQ2Z4a8rtlQJYvQKkAAABoQBYIIz4614aYCzRXHj1Rz3n5EvJOffMO9JRNi39Psf223DqAqEAoQBYIOC3eK4Vi+GfsUb9rTHWc9QixF8I8ImERIYFtnjhgD8FA6UAUMDOKA5DPuOIQp1D3s/BgeMBAAIAA6EAWCANaQBPmEJ27YRdUC9uGimBllZhWOKOiGMP8nnRbWisXQRYLdos7n+N+DmyRIMgnAM1EOffx9Q9QKjwyeibARDAv9ePj9rJUqG5GrbjhE6XnQ==","sender":"8804a06b989632be","recipient":"8fa2d9790ffc8e80"},"from":"[redacted]","type":"conversation.otr-message-add"}
couldn't find session
load_prekey 0
(node:24372) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property '0' of undefined
(node:24372) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by ffflorian** [comment]
My guess is, it has something to do with your modified (and deprecated) [cryptobox.js](https://github.com/damirn/cryptobox.js). I think the project should rather use [wire-webapp-cryptobox](https://github.com/wireapp/wire-webapp-cryptobox/).

**Comment by ffflorian** [comment]
Well, it .. fixed itself on its own. Nice :+1:

**Comment by ffflorian** [comment]
It worked once. Now not anymore :( Same error.

**Comment by mrpinghe** [comment]
I'm encountering the exact same problem

```
couldn't find session
load_prekey 0
(node:15717) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 4): TypeError: Cannot read property '0' of undefined
```

Looking at the log, it seems to have added prekey

```
got cryptobox
add_prekey
add_prekey
add_prekey
add_prekey
add_prekey
add_prekey
add_prekey
add_prekey
add_prekey
pQABA[redacted]JBPY=
pQABA[redacted]JBPY=
pQABA[redacted]JBPY=
pQABA[redacted]JBPY=
pQABA[redacted]JBPY=
pQABA[redacted]JBPY=
pQABA[redacted]JBPY=
pQABA[redacted]JBPY=
pQABA[redacted]9g==
```


All redacted strings are different, despite the unredacted portion is the same for all but one.

**Comment by mrpinghe** [comment]
A little more info...

- I just used echo_text_bot.js, and modified with my own port, keys, and auth token
- The callback for join and leave work fine, and the console.log got invoked in those callbacks and messages getting logged
- This happens for message callback, before actually processing any code in the callback

**Comment by mrpinghe** [comment]
Hi @dkovacevic 
While I switched to the Java API and got it working, I'm wondering whether there is any other details you need from me to help me/us troubleshoot this crypto related issue?

Based on the experience with the java version, I'm guessing the cert is not validated, although there is no explicit indication of that, as is the case with echo.yaml of the java version, in the node version.

The devbot was also able to get successful response after requesting /bot/status with the java bot, while the node version can see the request, but doesn't seem to give devbot what he had in mind.

Anyway, please let me know if there is any additional info I can provide to help.

Thanks!

**Comment by mrpinghe** [comment]
A bit more debug info...

modified the echo_text_bot.js a bit on the join callback

```
  bot.on('join', (members, conversation) => {
    console.log(`*** New members ${members} joined conversation ${conversation.id}`);
    bot.sendMessage('welcome', (sendStatus) => {
    });
  });
```

Log output
```
*** New members fe859794-6455-4966-890e-518ab6b9b992 joined conversation bb6de51d-0aa3-4130-9d61-2faae4c52c63
/root/node-bot/node_modules/wire-bot-sdk-node/lib/otr_manager.js:63
    Object.keys(devices).forEach((key) => {
           ^

TypeError: Cannot convert undefined or null to object
    at OtrManager.encryptForDevices (/root/node-bot/node_modules/wire-bot-sdk-node/lib/otr_manager.js:63:12)
    at Service.sendMessage (/root/node-bot/node_modules/wire-bot-sdk-node/lib/service.js:401:43)
    at BotInstance.sendMessage (/root/node-bot/node_modules/wire-bot-sdk-node/lib/bot_instance.js:60:18)
    at BotInstance.bot.on (/root/node-bot/echo_text_bot.js:42:9)
    at emitTwo (events.js:106:13)
    at BotInstance.emit (events.js:191:7)
    at BotInstance.onConversationMemberJoin (/root/node-bot/node_modules/wire-bot-sdk-node/lib/bot_instance.js:40:10)
    at Service.conversationMemberJoin (/root/node-bot/node_modules/wire-bot-sdk-node/lib/service.js:332:36)
    at Service.handleMessagesImpl (/root/node-bot/node_modules/wire-bot-sdk-node/lib/service.js:233:12)
    at Service.handleMessages (/root/node-bot/node_modules/wire-bot-sdk-node/lib/service.js:224:12)
```

Okay. I will stop now

**Comment by dkovacevic** [comment]
Thanks @mrpinghe for this detailed analysis and your patience. Let;s connect on Wire to debug this case. My username is: @dejan

**Comment by damirn** [comment]
@mrpinghe: your second problem looks unrelated to the first one, we should create a separate ticket for it.

**Comment by mrpinghe** [comment]
@damirn ah, sorry, I thought since they both were related to encryption, one is for decrypting messages when coming in, and one is for encrypting messages before sending out, they would be the same issue. Opening up a new issue now...
