### ISSUE TITLE
Installation description is misleading

### ISSUE THREAD

**Issue by ffflorian** [wireapp/bot-sdk-node#4]
At [Installation](https://github.com/wireapp/bot-sdk-node#installation) the Readme says
```
npm install --save wire-bot-node
```

But the Bot SDK is not on npm yet:
`npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/wire-bot-node`

Also I can't just `require` the SDK because the `package.json` is not correct. Its `main` entry is leading to a non-existent `index.js` file (see [package.json#L5](https://github.com/wireapp/bot-sdk-node/blob/master/package.json#L5)).

So what I needed to do, was:
```sh
cd my-project
git clone https://github.com/wireapp/bot-sdk-node.git
cd bot-sdk-node
npm install
```

And in my project I had to add
```js
const service = require('./bot-sdk-node/lib/service');
```

**Comment by damirn** [comment]
Confirmed; it should be corrected now.

**Comment by ffflorian** [comment]
Okay, thanks. But what about my pull request?

**Comment by damirn** [comment]
Merged.
